//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.ContractManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        public int id { get; set; }
        public string contract_title { get; set; }
        public Nullable<int> vendorid { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> annualrenewaldate { get; set; }
        public Nullable<System.DateTime> procereviewdate { get; set; }
        public string contracttype { get; set; }
        public Nullable<decimal> contractamount { get; set; }
        public Nullable<decimal> monthlycost { get; set; }
        public Nullable<decimal> currentcost { get; set; }
        public string department { get; set; }
        public string location { get; set; }
        public string contractmanagername { get; set; }
        public string contractmanageremail { get; set; }
        public string contractmanagerphone { get; set; }
        public string createduser { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    }
}
