//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.ContractManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_documents
    {
        public int id { get; set; }
        public Nullable<int> contractid { get; set; }
        public string docfilepath { get; set; }
        public string docbase64 { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> versionno { get; set; }
    }
}
